default: true
blanks-around-lists: false
line-length: false
no-inline-html: false
no-bare-urls: false
no-emphasis-as-heading: false
no-multiple-blanks: false
no-trailing-punctuation: false
no-duplicate-heading: false
heading-increment: false
heading-style:
  style: atx
ul-indent: false
ul-style:
  style: dash
fix: false
outputFormatters:
  - - markdownlint-cli2-formatter-codequality
  - - markdownlint-cli2-formatter-pretty
